"""Gradio page for the public demo, mounted on the FastAPI app at /ui."""

import logging

import gradio as gr

from app.core.rate_limit import client_ip
from app.schemas.ask import MAX_QUESTION_LENGTH

logger = logging.getLogger(__name__)

DESCRIPTION = """
Ask a question about the FCA Employee Handbook, a publicly available document.
Answers are generated by AI from the handbook and can be wrong, so check the cited pages.
Questions are stored to cache answers: don't enter personal information.
"""

EXAMPLES = [
    "What should we do if we suspect theft of information?",
    "How do I report sickness absence on my first day?",
    "Can I attend a medical appointment during working hours?",
]


def format_answer(response):
    if not response.sources:
        return response.answer
    pages = "\n".join(f"- {source.document}, page {source.page}" for source in response.sources)
    return f"{response.answer}\n\n**Sources**\n{pages}"


def make_responder(answer_question, limiter, trusted_hops):
    def respond(question, request: gr.Request):
        question = (question or "").strip()
        if not question:
            return "Type a question about the handbook first."
        if len(question) > MAX_QUESTION_LENGTH:
            return f"Please keep your question under {MAX_QUESTION_LENGTH} characters."

        fallback = request.client.host if request.client else None
        refusal = limiter.check(client_ip(request.headers, fallback, trusted_hops))
        if refusal:
            return refusal

        try:
            return format_answer(answer_question(question))
        except Exception:
            logger.exception("Failed to answer a UI question")
            return "Something went wrong while answering. Please try again, or rephrase the question."

    return respond


def build_ui(answer_question, limiter, trusted_hops):
    with gr.Blocks(title="Employee policy assistant") as ui:
        gr.Markdown("# Employee policy assistant")
        gr.Markdown(DESCRIPTION)
        question = gr.Textbox(
            label="Your question",
            placeholder="e.g. How much notice do I need to give for annual leave?",
            max_length=MAX_QUESTION_LENGTH,
        )
        ask = gr.Button("Ask the handbook", variant="primary")
        answer = gr.Markdown()
        gr.Examples(EXAMPLES, inputs=question)

        respond = make_responder(answer_question, limiter, trusted_hops)
        ask.click(respond, inputs=question, outputs=answer)
        question.submit(respond, inputs=question, outputs=answer)
    return ui
